package dev.trindadedev.template.ui.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.ui.graphics.Color

public val LightColorScheme: ColorScheme =
  ColorScheme(
    primary = Color(0xFF724F8F),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFF3DAFF),
    onPrimaryContainer = Color(0xFF2B0847),
    inversePrimary = Color(0xFFDFB7FE),
    secondary = Color(0xFF665A6E),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFEDDDF5),
    onSecondaryContainer = Color(0xFF211829),
    tertiary = Color(0xFF8A4D54),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFFFDADE),
    onTertiaryContainer = Color(0xFF380A13),
    background = Color(0xFFFFF7FF),
    onBackground = Color(0xFF1E1A22),
    surface = Color(0xFFFFF7FF),
    onSurface = Color(0xFF1E1A22),
    surfaceVariant = Color(0xFFE9DFEB),
    onSurfaceVariant = Color(0xFF4A454D),
    surfaceTint = Color(0xFF724F8F),
    inverseSurface = Color(0xFF342E37),
    inverseOnSurface = Color(0xFFF8EDF9),
    error = Color(0xFFB3261E),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFF9DEDC),
    onErrorContainer = Color(0xFF410E0B),
    outline = Color(0xFF7B747D),
    outlineVariant = Color(0xFFCDC3CE),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFFFFF7FF),
    surfaceDim = Color(0xFFDFD7E3),
    surfaceContainer = Color(0xFFF3EBF7),
    surfaceContainerHigh = Color(0xFFEEE5F1),
    surfaceContainerHighest = Color(0xFFE9DFEB),
    surfaceContainerLow = Color(0xFFF9F1FD),
    surfaceContainerLowest = Color(0xFFFFFFFF),
  )

public val DarkColorScheme: ColorScheme =
  ColorScheme(
    primary = Color(0xFFDFB7FE),
    onPrimary = Color(0xFF41205D),
    primaryContainer = Color(0xFF593875),
    onPrimaryContainer = Color(0xFFF3DAFF),
    inversePrimary = Color(0xFF724F8F),
    secondary = Color(0xFFD1C1D9),
    onSecondary = Color(0xFF372C3F),
    secondaryContainer = Color(0xFF4E4356),
    onSecondaryContainer = Color(0xFFEDDDF5),
    tertiary = Color(0xFFFFB2BA),
    onTertiary = Color(0xFF531F27),
    tertiaryContainer = Color(0xFF6E353D),
    onTertiaryContainer = Color(0xFFFFDADE),
    background = Color(0xFF18111A),
    onBackground = Color(0xFFE9DFEB),
    surface = Color(0xFF18111A),
    onSurface = Color(0xFFE9DFEB),
    surfaceVariant = Color(0xFF4A454D),
    onSurfaceVariant = Color(0xFFCDC3CE),
    surfaceTint = Color(0xFFDFB7FE),
    inverseSurface = Color(0xFFE9DFEB),
    inverseOnSurface = Color(0xFF342E37),
    error = Color(0xFFF2B8B5),
    onError = Color(0xFF601410),
    errorContainer = Color(0xFF8C1D18),
    onErrorContainer = Color(0xFFF9DEDC),
    outline = Color(0xFF968E98),
    outlineVariant = Color(0xFF4A454D),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFF3D3740),
    surfaceDim = Color(0xFF18111A),
    surfaceContainer = Color(0xFF231E26),
    surfaceContainerHigh = Color(0xFF2E2831),
    surfaceContainerHighest = Color(0xFF39333C),
    surfaceContainerLow = Color(0xFF1E1A22),
    surfaceContainerLowest = Color(0xFF130B16),
  )
